spring:
  datasource:
    password: root
    url: jdbc:mysql://localhost:3306/ticket_booking_v3
    username: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
      
server:
  servlet:
    context-path: /api
  port: 443
  ssl:
    key-store: classpath:keystore.p12
    key-store-password: password
    keyStoreType: PKCS12
    keyAlias: enablehttps
    