#spring:
#  data:
#    mongodb:
#      uri: mongodb://localhost:27017/auth-db

spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  datasource:
    url: jdbc:mysql://localhost:3306/auth_service?useSSL=false
    username: root #admin
    password: root #techo#2017
    driver-class-name: com.mysql.cj.jdbc.Driver
    #driver-class-name: com.mysql.jdbc.Driver